# Generated by Django 5.1.4 on 2026-07-10 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='', max_length=150)),
                ('bot_name', models.CharField(default='Assistant', max_length=80)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('bot_avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('launcher_icon', models.ImageField(blank=True, null=True, upload_to='launchers/')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=9)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=9)),
                ('header_bg_color', models.CharField(default='#0d6efd', max_length=9)),
                ('header_text_color', models.CharField(default='#ffffff', max_length=9)),
                ('background_color', models.CharField(default='#ffffff', max_length=9)),
                ('user_bubble_color', models.CharField(default='#0d6efd', max_length=9)),
                ('user_text_color', models.CharField(default='#ffffff', max_length=9)),
                ('bot_bubble_color', models.CharField(default='#f1f3f5', max_length=9)),
                ('bot_text_color', models.CharField(default='#212529', max_length=9)),
                ('font_family', models.CharField(default="'Segoe UI', Roboto, Arial, sans-serif", max_length=200)),
                ('launcher_position', models.CharField(choices=[('bottom-right', 'Bottom Right'), ('bottom-left', 'Bottom Left')], default='bottom-right', max_length=20)),
                ('header_title', models.CharField(default='', max_length=150)),
                ('header_subtitle', models.CharField(default='', max_length=200)),
                ('input_placeholder', models.CharField(default='Type your message...', max_length=150)),
                ('privacy_policy_url', models.URLField(blank=True, default='')),
                ('website_url', models.URLField(blank=True, default='')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=40)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_whatsapp', models.CharField(blank=True, default='', max_length=40)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('voice_enabled', models.BooleanField(default=True)),
                ('ai_system_prompt', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text="Unique key used by the embed/frontend to load this tenant's design.", max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('option_id', models.PositiveIntegerField(help_text='Matches the frontend flow id (e.g. 1=Appointment, 20=Cancel).')),
                ('label', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_options', to='api.chatbotdesign')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='chatbotdesign',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='api.tenant'),
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(max_length=500)),
                ('show_bot_icon', models.BooleanField(default=False)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_messages', to='api.chatbotdesign')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
