# Generated by Django 5.1.4 on 2026-07-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tenantowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuoption',
            name='category',
            field=models.CharField(choices=[('booking', 'Booking'), ('enquiry', 'Enquiry'), ('info', 'Info'), ('manage', 'Manage')], default='booking', max_length=20),
        ),
        migrations.AddField(
            model_name='menuoption',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='menuoption',
            name='flow_key',
            field=models.SlugField(blank=True, default='', help_text='Stable flow key, e.g. book_appointment.', max_length=80),
        ),
        migrations.AddField(
            model_name='menuoption',
            name='steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='menuoption',
            name='submit_url',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='menuoption',
            unique_together={('design', 'option_id')},
        ),
    ]
