# Generated by Django 5.1.4 on 2026-07-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_menuoption_flow_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuoption',
            name='step_config',
            field=models.JSONField(blank=True, default=list, help_text='Full configurable conversation steps (messages, choices, inputs).'),
        ),
    ]
