"""Initial flow catalog — used only by seed_flow_templates management command.

Runtime code reads from the FlowTemplate database table.
"""
from __future__ import annotations

MAIN_MENU_FLOWS: list[dict] = [
    {
        "id": 1,
        "key": "book_appointment",
        "label": "Appointment with doctor",
        "category": "booking",
        "submit_url": "patient-appoinment",
        "description": "Book an in-person doctor appointment.",
        "steps": [
            "self_or_other",
            "privacy_policy",
            "patient_name",
            "patient_age",
            "patient_gender",
            "phone",
            "branch",
            "department",
            "doctor",
            "date_slot",
            "confirm",
            "additional_info",
            "submit",
        ],
    },
    {
        "id": 2,
        "key": "find_doctor",
        "label": "Find doctor",
        "category": "booking",
        "submit_url": "patient-appoinment",
        "description": "Search doctors by branch and department.",
        "steps": [
            "self_or_other",
            "privacy_policy",
            "patient_details",
            "branch",
            "department",
            "doctor_picker",
            "submit",
        ],
    },
    {
        "id": 3,
        "key": "video_consultation",
        "label": "Book video consultation",
        "category": "booking",
        "submit_url": "book-video-consulting",
        "description": "Book a teleconsultation with a doctor.",
        "steps": [
            "self_or_other",
            "privacy_policy",
            "patient_details",
            "branch",
            "department",
            "doctor",
            "date_slot",
            "confirm",
            "submit",
        ],
    },
    {
        "id": 4,
        "key": "surgery_enquiry",
        "label": "Surgery enquiry",
        "category": "enquiry",
        "submit_url": "surgery-enquiry",
        "description": "Enquire about surgeries / procedures.",
        "steps": [
            "privacy_policy",
            "patient_details",
            "branch",
            "department",
            "surgery_list",
            "submit",
        ],
    },
    {
        "id": 5,
        "key": "international_patient",
        "label": "International patient query",
        "category": "enquiry",
        "submit_url": "international-enquiry",
        "description": "International / overseas patient enquiry.",
        "steps": ["self_or_other", "privacy_policy", "patient_details", "submit"],
    },
    {
        "id": 6,
        "key": "connect_with_us",
        "label": "Connect with us",
        "category": "info",
        "description": "Show phone, email, WhatsApp from tenant design.",
        "steps": ["show_contact"],
    },
    {
        "id": 7,
        "key": "customer_care",
        "label": "Connect with our Customercare",
        "category": "info",
        "description": "Customer care handoff (stub).",
        "steps": [],
    },
    {
        "id": 20,
        "key": "cancel_appointment",
        "label": "Cancel appointment",
        "category": "manage",
        "submit_url": "cancel-appointment",
        "description": "Cancel an existing booking by registered phone.",
        "steps": ["phone_lookup", "select_appointment", "confirm_cancel", "cancel_api"],
    },
    {
        "id": 21,
        "key": "reschedule_appointment",
        "label": "Reschedule appointment",
        "category": "manage",
        "submit_url": "reschedule-appointment",
        "description": "Reschedule an existing booking.",
        "steps": [
            "phone_lookup",
            "select_appointment",
            "confirm_reschedule",
            "pick_new_slot",
            "reschedule_api",
        ],
    },
]



FLOW_STEP_TEMPLATES: dict[str, list[dict]] = {
    "book_appointment": [
        {
            "key": "intro",
            "type": "message",
            "message": "Sure, I will help you with your booking.",
            "show_bot_icon": True,
            "enabled": True,
            "order": 0,
        },
        {
            "key": "self_or_other",
            "type": "choice",
            "message": "Do you want to book appointment for yourself or someone else?",
            "show_bot_icon": False,
            "options": [
                {"id": 8, "label": "Self"},
                {"id": 9, "label": "Family/Friends"},
            ],
            "enabled": True,
            "order": 1,
        },
        {
            "key": "privacy_policy",
            "type": "privacy",
            "message": "",
            "enabled": True,
            "order": 2,
        },
        {
            "key": "patient_name",
            "type": "input",
            "message": "Enter patient full name",
            "input_type": "name",
            "show_bot_icon": True,
            "enabled": True,
            "order": 3,
        },
        {
            "key": "patient_age",
            "type": "input",
            "message": "May I know your patient's age?",
            "input_type": "age",
            "show_bot_icon": True,
            "enabled": True,
            "order": 4,
        },
        {
            "key": "patient_gender",
            "type": "choice",
            "message": "May I know your patient's gender?",
            "show_bot_icon": True,
            "options": [
                {"id": 12, "label": "Male"},
                {"id": 13, "label": "Female"},
            ],
            "enabled": True,
            "order": 5,
        },
        {
            "key": "phone",
            "type": "input",
            "message": "Enter patient 10-digit mobile number (type or speak below).",
            "input_type": "phoneNumber",
            "show_bot_icon": True,
            "enabled": True,
            "order": 6,
        },
        {
            "key": "branch",
            "type": "branch",
            "message": "Please choose your location which speciality appointment are you looking for",
            "show_bot_icon": True,
            "enabled": True,
            "order": 7,
        },
        {
            "key": "department",
            "type": "department",
            "message": "Click for speciality",
            "show_bot_icon": True,
            "enabled": True,
            "order": 8,
        },
        {
            "key": "doctor_slot",
            "type": "doctor_slot",
            "message": "",
            "enabled": True,
            "order": 9,
        },
        {
            "key": "additional_info",
            "type": "additional_info",
            "message": "Do you want to provide any additional info?",
            "enabled": True,
            "order": 10,
        },
        {
            "key": "submit",
            "type": "submit",
            "message": "Thank you for submitting your details our team would get in touch with you shortly",
            "show_bot_icon": True,
            "enabled": True,
            "order": 11,
        },
    ],
    "cancel_appointment": [
        {
            "key": "intro",
            "type": "message",
            "message": "Sure, I can help you cancel an appointment.",
            "show_bot_icon": True,
            "enabled": True,
            "order": 0,
        },
        {
            "key": "phone_lookup",
            "type": "input",
            "message": "Please enter the registered 10-digit mobile number used while booking.",
            "input_type": "managePhone",
            "show_bot_icon": False,
            "enabled": True,
            "order": 1,
        },
        {
            "key": "select_appointment",
            "type": "select_appointment",
            "message": "Select the appointment you want to cancel.",
            "show_bot_icon": True,
            "enabled": True,
            "order": 2,
        },
        {
            "key": "confirm_cancel",
            "type": "choice",
            "message": "Are you sure you want to cancel this appointment?",
            "show_bot_icon": True,
            "options": [
                {"id": 22, "label": "Yes, cancel it"},
                {"id": 23, "label": "No, keep it"},
            ],
            "enabled": True,
            "order": 3,
        },
        {
            "key": "cancel_success",
            "type": "submit",
            "message": "Your appointment has been cancelled successfully.",
            "show_bot_icon": True,
            "enabled": True,
            "order": 4,
        },
    ],
    "reschedule_appointment": [
        {
            "key": "intro",
            "type": "message",
            "message": "Sure, I can help you reschedule an appointment.",
            "show_bot_icon": True,
            "enabled": True,
            "order": 0,
        },
        {
            "key": "phone_lookup",
            "type": "input",
            "message": "Please enter the registered 10-digit mobile number used while booking.",
            "input_type": "managePhone",
            "show_bot_icon": False,
            "enabled": True,
            "order": 1,
        },
        {
            "key": "select_appointment",
            "type": "select_appointment",
            "message": "Select the appointment you want to reschedule.",
            "show_bot_icon": True,
            "enabled": True,
            "order": 2,
        },
        {
            "key": "confirm_reschedule",
            "type": "choice",
            "message": "Do you want to reschedule this appointment?",
            "show_bot_icon": True,
            "options": [
                {"id": 24, "label": "Yes, reschedule"},
                {"id": 25, "label": "No"},
            ],
            "enabled": True,
            "order": 3,
        },
        {
            "key": "pick_new_slot",
            "type": "pick_new_slot",
            "message": "Please choose a new date and time slot.",
            "show_bot_icon": True,
            "enabled": True,
            "order": 4,
        },
        {
            "key": "reschedule_success",
            "type": "submit",
            "message": "Your appointment has been rescheduled successfully.",
            "show_bot_icon": True,
            "enabled": True,
            "order": 5,
        },
    ],
    "connect_with_us": [
        {
            "key": "intro",
            "type": "message",
            "message": "Sure, here are the ways you can connect with us.",
            "show_bot_icon": True,
            "enabled": True,
            "order": 0,
        },
        {
            "key": "show_contact",
            "type": "show_contact",
            "message": "Connect with us",
            "show_bot_icon": False,
            "enabled": True,
            "order": 1,
        },
    ],
}


